[package]
name = "homepage"
version = "0.1.0"
authors = ["Kevin Watters <kevinwatters@gmail.com>"]

[build-dependencies]
askama = "*"

[dependencies]
askama = "*" # templates

gotham = "*"

hyper = "0.11"
futures = "0.1"
mime = "0.3"

serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"

chrono = { version = "*", features = ["serde"] }

shellexpand = "*"

[dependencies.nom]
version = "^3.2"

[dependencies.lazy_static]
version = "1.0.0"

[dependencies.regex]
version = "^0.2"
