[package]
name = "homepage"
version = "0.1.0"
authors = ["Kevin Watters <kevinwatters@gmail.com>"]

[build-dependencies]
askama = "*"

[dependencies]
askama = "*" # templates

gotham = "*"

hyper = "0.11"
futures = "0.1"
mime = "0.3"

serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"

todo-txt = "*"

shellexpand = "*"

